quality.gradle

The only one not showing errors on console yet is FindBugs but it seems there is no way...if its a problem at some point we always can add on .travis.yml: `after_failure: cat .../report.xml`

Show Checkstye errors on console if Travis

---

build.gradle
leku/build.gradle

Here we are using our custom SchibstedSpain fork of the library,
because the main library is not updated to work with GooglePlayServices 9.4.0

Update reactive location library.

---

README.md
app/build.gradle
app/src/main/java/com/schibsted/mappicker/MainActivity.java
leku/build.gradle
leku/lib-proguard-rules.txt
leku/src/main/java/com/schibstedspain/leku/LocationPickerActivity.java

Added consumerProguardFiles to avoid the user need to add manually the proguard rules, solves issue #34 
Added parameter to force return RESULT_OK on back pressed, solves issue #33

Consumer proguard files

---

.travis.yml
README.md
app/build.gradle
build.gradle
leku/build.gradle
leku/src/main/java/com/schibstedspain/leku/LocationPickerActivity.java
leku/src/main/java/com/schibstedspain/leku/geocoder/GeocoderPresenter.java
leku/src/main/java/com/schibstedspain/leku/geocoder/GeocoderViewInterface.java

Related to the feature requested from issue #55

Added Auto-complete feature for the search view (related to issue #55)

---

README.md
app/src/main/java/com/schibsted/mappicker/MainActivity.java
leku/build.gradle
leku/src/main/java/com/schibstedspain/leku/CountryLocaleRect.java

When zone set to "es_ES" or any zone not in the Java Locale enum does not return the correct search zone
Solves the Issue #109

Solved issue where country locale zone not retrieve correctly

---

leku/src/main/java/com/schibstedspain/leku/geocoder/AndroidGeocoderDataSource.java

We have this crash:
```
Fatal Exception: io.reactivex.exceptions.UndeliverableException: java.io.IOException: grpc failed
at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:349)
at io.reactivex.internal.operators.observable.ObservableCreate$CreateEmitter.onError(ObservableCreate.java:74)
at com.schibstedspain.leku.geocoder.AndroidGeocoderDataSource.lambda$getFromLocation$2$AndroidGeocoderDataSource(AndroidGeocoderDataSource.java:52)
at com.schibstedspain.leku.geocoder.AndroidGeocoderDataSource$$Lambda$2.subscribe(Unknown Source)
at io.reactivex.internal.operators.observable.ObservableCreate.subscribeActual(ObservableCreate.java:40)
at io.reactivex.Observable.subscribe(Observable.java:10955)
at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run( …
```

Fix Undeliverable exception in RxJava 2

---

app/build.gradle
leku/build.gradle
leku/src/main/java/com/schibstedspain/leku/geocoder/GeocoderPresenter.java

Because it's not mandatory the use of Google places API. Also Updated libraries.
It solves the Issue #156

Added new constructor for GeocoderPresenter

---

leku/src/main/java/com/schibstedspain/leku/LocationPickerActivity.kt

#164 dynamically ask for location permission if it was denied previously
When location permission is denied if we click on the "my location" fav button we need to ask again for the permission.
Manually
No screens

[#164] Ask for location permission on Fav button "my location"

---

README.md

There is an issue with the Bintray plugin so it's not possible for now to upload a new version, so for now I've decided to revert the Readme changes related to the new version to not confuse the users.

Reverted version on Readme until Bintray plugin fixed

---

build.gradle

We cannot publish a new release version because the Novoda plugin fails with the latest gradle wrapper. So we are going to test the latest snapshot version that upgrades the plugin to a newer gradle version.
No tests
No Screens

Try the Novoda plugin SNAPSHOT-6 to release the new leku version

---

leku/src/main/java/com/schibstedspain/leku/LocationPickerActivity.kt

removed depricate param for getGeoDataClient.
reference:https://developers.google.com/android/reference/com/google/android/gms/location/places/Places.html#getGeoDataClient(android.app.Activity)
It has been stated in google docs to use the updated method for creating getGeoDataClient object.

removed depricated method parameter for GeoDataClient Object

---

leku/build.gradle

We need to exclude Kotlin files when executing javadoc task

Exclude kotlin files for Javadoc

---

leku/src/main/java/com/schibstedspain/leku/geocoder/GoogleGeocoderDataSource.kt

[#227](https://github.com/AdevintaSpain/Leku/issues/277)
NetworkException was not handled correctly:
> Fatal Exception: io.reactivex.exceptions.UndeliverableException
> The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | HTTP error code: 400
No screens

[ISSUE 227] Solve unhandled NetworkException issue

---

leku/build.gradle
leku/lib-proguard-rules.txt
leku/src/main/java/com/schibstedspain/leku/LocationPickerActivity.kt
leku/src/main/java/com/schibstedspain/leku/geocoder/GeocoderPresenter.kt
leku/src/main/java/com/schibstedspain/leku/utils/BaseLocationObservableOnSubscribe.java
leku/src/main/java/com/schibstedspain/leku/utils/BaseObservableOnSubscribe.java
leku/src/main/java/com/schibstedspain/leku/utils/LastKnownLocationObservableOnSubscribe.java
leku/src/main/java/com/schibstedspain/leku/utils/ReactiveLocationProvider.kt

`com.github.MarsXan:Android-ReactiveLocation` doesn't get updates since 3 years ago. It depends on android support and it depends on RxJava2. For that reason I'm removing that dependency.
Luckly we were using only one little feature from it so I just copied the necessary code to the project to keep it working.
Then I moved the code to RxJava3 so I removed our dependency with RxJava2 too.

Remove the last RxJava2 dependency

---

gradle.properties
leku/build.gradle

Depends on #301 
Now that we removed Android-ReactiveLocation we don't have any dependency using to the old android support. So we can disable jetifier 🎉. Happy faster builds (no fast, just faster. Remeber we are still using Android 😛)

Disable jetifier

---

leku/src/main/java/com/adevinta/leku/geocoder/timezone/GoogleTimeZoneDataSource.kt

Maybe related to #308 
Clicking on the map launches two calls, from `GeocoderPresenter.getInfoFromLocation(LatLng)`:
1. Geocoder from LatLng
2. Get Timezone
If no ApiKey is provided to work with the TimeZone API, an IllegalStateException is thrown, causing the `getInfoFromLocation` to fail and the address obtained from the Geocoder call is not painted in the address box.
Before | After
---|---

Handle exception thrown by TimeZoneApi when getting timezone without api-key

---

leku/src/main/java/com/adevinta/leku/LocationPickerActivity.kt

No issue
Depending on how the user types the address they want to search for, the addresses displayed in the results list are not readable.
The `Address` object already has an` addressLine` property that contains the full human readable address.
In this PR I'm using this property, if it has a value. If not, the full address is built as before.
Before | After
---|---

Show complete addressLine in search list

---

leku/src/main/java/com/adevinta/leku/LocationPickerActivity.kt

No related issue
When searching, the current implementation is making too many requests to the geocoder, with the corresponding update of the results list, one for each request. You can see the effect in the first columns of screenshots.
To improve the UX in this part, my idea is to rethink the debounce implementation, applying it to the `onTextChangeListener`. This way the request itself will be done only after `DEBOUNCE_TIME` milliseconds has passed without changing the term of search.
Before | After
---|---

Reduce geocoder calls and UI updates when searching

---

app/build.gradle
app/src/main/java/com/adevinta/mappicker/MainActivity.kt
build.gradle
gradle/wrapper/gradle-wrapper.properties
leku/build.gradle
leku/src/androidTest/AndroidManifest.xml
leku/src/androidTest/java/com/adevinta/leku/LocationPickerActivityShould.kt
leku/src/androidTest/java/com/adevinta/leku/geocoder/api/AddressBuilderShould.kt
leku/src/main/java/com/adevinta/leku/LekuPoi.kt
leku/src/main/java/com/adevinta/leku/LocationPickerActivity.kt
leku/src/main/java/com/adevinta/leku/LocationSearchAdapter.kt
leku/src/main/java/com/adevinta/leku/geocoder/AndroidGeocoderDataSource.kt
leku/src/main/java/com/adevinta/leku/geocoder/GeocoderDataSourceInterface.kt
leku/src/main/java/com/adevinta/leku/geocoder/GeocoderPresenter.kt
leku/src/main/java/com/adevinta/leku/geocoder/GeocoderRepository.kt
leku/src/main/java/com/adevinta/leku/geocoder/GoogleGeocoderDataSource.kt
leku/src/main/java/com/adevinta/leku/geocoder/places/GooglePlacesDataSource.kt
leku/src/main/java/com/adevinta/leku/geocoder/timezone/GoogleTimeZoneDataSource.kt
leku/src/main/java/com/adevinta/leku/locale/SearchZoneRect.kt
leku/src/main/java/com/adevinta/leku/permissions/PermissionUtils.kt
leku/src/main/java/com/adevinta/leku/utils/ReactiveLocationProvider.kt

In order to migrate all the library from RxJava to Kotlin Coroutines we have migrated the GeocoderRepository to Coroutines.
No screens

Migrate Geocoder to coroutines

---

app/build.gradle
app/src/main/java/com/adevinta/mappicker/MainActivity.kt
build.gradle
leku/build.gradle
leku/src/main/java/com/adevinta/leku/LocationPickerActivity.kt

No Issue
We have replaced the deprecated "startActivityForResult" method with the new activity result launcher.
No screens

[NO ISSUE] Replaced deprecated onActivityResult method with the new activity result launcher

---

README.md
app/src/main/java/com/adevinta/mappicker/MainActivity.kt
app/src/main/java/com/adevinta/mappicker/SampleApplication.kt
app/src/main/res/values/strings.xml
docs/customization.md
docs/extra.md
docs/getting_started.md
gradle.properties
leku/src/main/java/com/adevinta/leku/LocationPickerActivity.kt

No issue
We have found that maps initialization was required before launching LocationPickeractivity, to avoid this initialization we have moved it to the builder to avoid extra unnecessary code.
No screens

[NO ISSUE] Solved Maps initialization problem

---

README.md
app/src/main/res/values/strings.xml
docs/getting_started.md
gradle.properties

Version 11.1.1

---

leku/src/main/java/com/adevinta/leku/LocationPickerActivity.kt

When we are initializing Leku without coordinates (example: we haven't given location access beforehand), we are performing a search and displaying results. This ends up blocking the buttons in the screen.
Set a default location, so we are not going to trigger the location search. Then, when user has given location access, everything's still going to work as expected.
Before:
https://github.com/AdevintaSpain/Leku/assets/6688705/f070f77c-6415-48e3-9fc7-35da3aed07aa
After:
https://github.com/AdevintaSpain/Leku/assets/6688705/f5972769-cc96-4728-b99b-097556cd73a5

When no location in the bundle, we are still doing a search

---

app/src/main/java/com/adevinta/mappicker/MainActivity.kt
leku/src/main/java/com/adevinta/leku/LocationPickerActivity.kt

I missed a really important point in my last PR. This default location is only needed when permissions aren't granted. Else, it's not necessary because we are going to retrieve the location we are at.

Scmi 112253 no coordinates in bundle show results

---

app/src/main/java/com/adevinta/mappicker/MainActivity.kt
leku/src/main/java/com/adevinta/leku/LocationPickerActivity.kt

I didn't notice the negation was missing. Amazing. Kill me please.

Fix the condition
