AdevintaSpain/Leku

.travis.yml, app/build.gradle, app/src/main/AndroidManifest.xml, leku/build.gradle, leku/src/main/res/layout-land/activity_location_picker.xml, leku/src/main/res/layout-normal-v21/activity_location_picker.xml, leku/src/main/res/layout-normal/activity_location_picker.xml, leku/src/main/res/layout-xlarge-v21/activity_location_picker.xml, leku/src/main/res/layout-xlarge/activity_location_picker.xml, leku/src/main/res/layout/activity_location_picker.xml, leku/src/main/res/menu/toolbar_menu.xml, leku/src/main/res/values-es/strings.xml, leku/src/main/res/values/strings.xml
=> Solve Lint issues

README.md
=> Added message to explain that it supports runtime permissions

.travis.yml, README.md, app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/java/com/schibsted/mappicker/MainActivity.java, app/src/main/res/values-w820dp/dimens.xml, app/src/main/res/values/dimens.xml, leku/build.gradle, leku/src/main/java/com/schibstedspain/leku/LocationPickerActivity.java, leku/src/main/res/layout/toolbar_search.xml
Upgraded play services to 9.4.0 and support library to 24.1.1. Refactored LocationPickerActivity to meet the new requirements
Related to issue #16
=> New library version 2.0.0. Upgraded play services and support library

app/src/main/res/layout/activity_main.xml
It was a LinearLayout some time ago? :·)
=> Remove unneeded orientation in a FrameLayout

README.md
With this, we show at Readme that developers should add SchibstedSpain maven repository in their `build.gradle` files
=> Update Leku README with AndroidReactiveLocation patch

leku/src/main/java/com/schibstedspain/leku/LocationPickerActivity.java, leku/src/main/java/com/schibstedspain/leku/permissions/PermissionUtils.java
This PR fixes issue #24 opened by @rocboronat.
I've added an option to get `LastKnowLocation`once user accepts the permission. I'm not sure if it should get last location, or ask for location update
=> Point map on user location after accept permission

README.md, build.gradle, gradle/wrapper/gradle-wrapper.properties, leku/build.gradle, leku/src/main/java/com/schibstedspain/leku/LocationPickerActivity.java
Solved issue when clicking on voice icon then changes orientation raises a Null Pointer Exception.
=> Null Pointer Exception on change orientation

.gitignore, README.md, app/src/main/AndroidManifest.xml, build.gradle
Also updated project for AS 2.2
=> Now for Android API >=21 you need use-feature for GPS

.travis.yml, app/build.gradle, build.gradle, leku/build.gradle, leku/src/main/res/layout-land/activity_location_picker.xml, leku/src/main/res/layout-normal-v21/activity_location_picker.xml, leku/src/main/res/layout-normal/activity_location_picker.xml, leku/src/main/res/layout-xlarge-v21/activity_location_picker.xml, leku/src/main/res/layout-xlarge/activity_location_picker.xml, leku/src/main/res/layout/activity_location_picker.xml
=> Now FABs follow Theme colours

README.md, app/src/main/AndroidManifest.xml, leku/build.gradle, leku/src/main/res/layout-land/activity_location_picker.xml, leku/src/main/res/layout-normal-v21/activity_location_picker.xml, leku/src/main/res/layout-normal/activity_location_picker.xml, leku/src/main/res/layout-xlarge-v21/activity_location_picker.xml, leku/src/main/res/layout-xlarge/activity_location_picker.xml, leku/src/main/res/layout/activity_location_picker.xml
=> New Version 2.3.1. That solves a RTL layout issue

app/src/main/java/com/schibsted/mappicker/MainActivity.java, app/src/main/res/layout/activity_main.xml, app/src/main/res/values/strings.xml, leku/src/main/java/com/schibstedspain/leku/LekuPoi.java, leku/src/main/java/com/schibstedspain/leku/LocationPickerActivity.java, leku/src/main/java/com/schibstedspain/leku/tracker/TrackEvents.java
This PR allows to send a lits of POIs that will be displayed on MAP, and user will be able to select them.
=> Add pois selection option

leku/src/main/java/com/schibstedspain/leku/LocationPickerActivity.java
when the activity is not active any more.
=> Removed TextWatcher listener on destroy to avoid issues

.github/ISSUE_TEMPLATE.md
Need because we don't receive so many info about problems submitted.
=> Added Issue Template

README.md, app/src/main/java/com/schibsted/mappicker/MainActivity.java, leku/src/main/java/com/schibstedspain/leku/LocationPickerActivity.java
Added possibility to enable/disable satalite feature
=> Added possibility to enable/disable satalite feature

README.md
WRITE_EXTERNAL_STORAGE is not mandatory like stated in the readme:
"You must add the following permissions"
Only changed the readme
=> WRITE_EXTERNAL_STORAGE optional

app/build.gradle, build.gradle, leku/build.gradle
=> Update gradle version

README.md, leku/src/main/java/com/schibstedspain/leku/LocationPickerActivity.java
Add the ability to prevent Leku from requesting location permissions via an intent extra
=> Issue 81 location permission fix

leku/src/main/java/com/schibstedspain/leku/LocationPickerActivity.java, leku/src/main/java/com/schibstedspain/leku/tracker/TrackEvents.java
We still have Log reference that are being shown if Google Api fails. So we need to remove it and track them if necessary.
=> Removed Log reference from LocationPickerActivity 

leku/src/main/java/com/schibstedspain/leku/LocationPickerActivity.java, leku/src/main/java/com/schibstedspain/leku/geocoder/AndroidGeocoderDataSource.java, leku/src/main/java/com/schibstedspain/leku/geocoder/GeocoderInteractorDataSource.java, leku/src/main/java/com/schibstedspain/leku/geocoder/GeocoderPresenter.java, leku/src/main/java/com/schibstedspain/leku/geocoder/GeocoderRepository.java, leku/src/main/java/com/schibstedspain/leku/geocoder/GoogleGeocoderDataSource.java
After https://github.com/SchibstedSpain/Leku/pull/95 i move code to a `GeocoderRepository` so in a future, if we add a new `Geocode` it can be added without change presenter.
@sergiandreplace please take a look on this!
=> Refactor GeocoderPresenter with GeocoderRepository

.github/CODEOWNERS, build.gradle
=> Solved mistake of codeowners file and updated gradle plugin

README.md, leku/build.gradle, leku/src/main/java/com/schibstedspain/leku/LocationPickerActivity.java
It's a Hotfix. Solves issue with location static values.
=> [HOTFIX] New version 3.4.1.

.gitignore, README.md, leku/build.gradle, leku/src/main/java/com/schibstedspain/leku/LocationPickerActivity.java
=> Solves the issue: When address is one line does not appear the accept button

README.md, leku/build.gradle, leku/src/main/java/com/schibstedspain/leku/CountryLocaleRect.java
=> Added Germany, DACH, UAE and India as new locales.

README.md, app/src/debug/res/values/strings.xml, leku/build.gradle, leku/src/main/java/com/schibstedspain/leku/LocationPickerActivity.java
Solved issue that prevents showing address when selecting new location
=> Issue with address

app/build.gradle, leku/build.gradle, leku/src/main/java/com/schibstedspain/leku/geocoder/AndroidGeocoderDataSource.java, leku/src/main/java/com/schibstedspain/leku/geocoder/GeocoderInteractorDataSource.java, leku/src/main/java/com/schibstedspain/leku/geocoder/GeocoderPresenter.java, leku/src/main/java/com/schibstedspain/leku/geocoder/GeocoderRepository.java, leku/src/main/java/com/schibstedspain/leku/geocoder/GoogleGeocoderDataSource.java
It still need to change ReactiveLocation library that still use RxJava1
=> Upgraded project to RxJava2

leku/src/main/java/com/schibstedspain/leku/LocationPickerActivity.java
Hi there. Found a bug with hiding zip code, street and city views. Fixed
=> fix withCityHidden, withZipCodeHidden and withStreetHidden options

leku/build.gradle, leku/src/main/java/com/schibstedspain/leku/LocationPickerActivity.java, leku/src/main/java/com/schibstedspain/leku/geocoder/GeocoderPresenter.java
RxJava 1 removed. Please release new artifact to jcenter
=> *remove RxJava 1. Update libs

build.gradle, leku/src/main/java/com/schibstedspain/leku/LocationPickerActivity.java
Solved issue where does not show one result in list and does not search on remove chars.
=> Search view list not shown issue solved

.travis.yml, build.gradle, leku/build.gradle
Twitter python gist removed and added the new twitter gradle plugin implementation. More info: [https://github.com/ferranpons/twitter-gradle-plugin](https://github.com/ferranpons/twitter-gradle-plugin)
=> Added Twitter Gradle Plugin

leku/src/main/java/com/schibstedspain/leku/CountryLocaleRect.java
=> Pakistan Locale support

README.md
It was not updated since version 1.0.0.
=> Updated Demo gif

README.md
Badge that shows if the repo is trending, with statistics of stargazers evolution.
[http://starveller.sigsev.io/SchibstedSpain/Leku](http://starveller.sigsev.io/SchibstedSpain/Leku)
=> Added Trending badge

leku/src/main/java/com/schibstedspain/leku/CountryLocaleRect.kt
=> Added Vietnam search zone

app/src/main/java/com/schibsted/mappicker/MainActivity.kt, leku/src/main/java/com/schibstedspain/leku/LocationPickerActivity.kt
=> [#161] Hide toolbar if play services not available

README.md, app/src/main/java/com/schibsted/mappicker/MainActivity.kt, leku/src/main/java/com/schibstedspain/leku/LocationPickerActivity.kt
#110 Option to disable voice search (enhancement)
Option into the Builder to disable voice search
Manually
No screens
=> [#110] Added the option to hide the Voice search option

README.md, app/src/main/java/com/schibsted/mappicker/MainActivity.kt, leku/build.gradle, leku/lib-proguard-rules.txt, leku/src/main/java/com/schibstedspain/leku/LocationPickerActivity.kt, leku/src/main/java/com/schibstedspain/leku/geocoder/GeocoderPresenter.kt, leku/src/main/java/com/schibstedspain/leku/geocoder/GeocoderViewInterface.kt, leku/src/main/java/com/schibstedspain/leku/geocoder/timezone/GoogleTimeZoneDataSource.kt
#88 Please include timezone
Added Google Time Zone API service to the library and added the option to include it on the location results.
**NOTE:** documentation for this new feature will be described in the next PR because README need to be reworked due to the migration to Kotlin
Manually
No screens
=> [#88] Time zone feature added

README.md
=> Changed Java code to Kotlin in the README

build.gradle
=> Updated Kotlin version to 1.2.71

app/src/main/java/com/schibsted/mappicker/MainActivity.kt, config/detekt/detekt-config.yml, leku/src/main/java/com/schibstedspain/leku/LekuPoi.kt, leku/src/main/java/com/schibstedspain/leku/LocationPickerActivity.kt, leku/src/main/java/com/schibstedspain/leku/geocoder/GoogleGeocoderDataSource.kt, leku/src/main/java/com/schibstedspain/leku/geocoder/api/AddressBuilder.kt, leku/src/main/java/com/schibstedspain/leku/geocoder/api/NetworkClient.kt
When entering on flight mode or no internet connection available when selecting a new location it crashes.
Related to issue #188 
Manually
No screens
=> Solved issue when no internet connection available

build.gradle, leku/build.gradle
Novoda plugin is not working properly so we decided to switch to Bintray oficial gradle plugin
=> Use Bintray gradle plugin instead of Novoda plugin

leku/build.gradle, scripts/bintrayUpload.sh
Fine tuning the upload to bintray
=> Added FileSpec property because is not uploading the artifact

leku/build.gradle
This solved the issues with the bintray gradle plugin. It had an incorrect configuration.
=> Applied the correct config for Bintray Upload

leku/build.gradle
We have problems with 'aar' when is uploaded to bintray is not getting correctly the sources.
Manually
=> Added javadoc and sources because aar is not being generated correctly

leku/build.gradle
There was an issue when generating the pom. Some dependencies were not found.
Manually in local
No screens
=> Corrected issue with pom generated

.travis.yml, app/build.gradle, app/src/main/java/com/schibsted/mappicker/MainActivity.kt, gradle.properties, leku/build.gradle, leku/src/androidTest/java/com/schibsted/leku/LocationPickerActivityShould.kt, leku/src/androidTest/java/util/OrientationChangeAction.kt, leku/src/androidTest/java/util/PermissionGranter.kt, leku/src/main/java/com/schibstedspain/leku/LocationPickerActivity.kt, leku/src/main/java/com/schibstedspain/leku/permissions/PermissionUtils.kt, leku/src/main/res/layout-land/leku_activity_location_picker.xml, leku/src/main/res/layout-normal-v21/leku_activity_location_picker.xml, leku/src/main/res/layout-normal/leku_activity_location_picker.xml, leku/src/main/res/layout-xlarge-v21/leku_activity_location_picker.xml, leku/src/main/res/layout-xlarge/leku_activity_location_picker.xml, leku/src/main/res/layout/leku_activity_location_picker.xml, leku/src/main/res/layout/leku_toolbar_search.xml
=> Project migrated to AndroidX

README.md
=> Removed trending badge because is not working any more

PULL_REQUEST_TEMPLATE.md
=> [NO ISSUE] New PR template

README.md, app/src/main/java/com/schibsted/mappicker/MainActivity.kt, leku/src/main/java/com/schibstedspain/leku/LocationPickerActivity.kt
#235 
We have added the option to hide the street name with "Unnamed Road" on the address.
Manually
Before | After
---|---
=> [ISSUE #235] Added the option to hide "Unnamed Road" in Address

leku/src/main/java/com/schibstedspain/leku/LocationPickerActivity.kt
https://github.com/SchibstedSpain/Leku/pull/238#discussion_r275039144
Remove "Unnamed Road - " from street if not `isUnnamedRoadVisible`
Before | After
---|---
=> Remove "Unnamed Road - " from street info

leku/src/main/java/com/schibstedspain/leku/locale/DefaultCountryLocaleRect.kt
No issue
Added support for Ireland
Before | After
---|---
=> Added Ireland to Country Locale Rect.

leku/build.gradle
We need to fix the path in order to be able to upload a new aar to bintray
=> Publishing aar path fix

app/build.gradle, leku/build.gradle
no issue
The objective is to have up-to-date the Appcompat library.
no screens
=> Updated appcompat library

build.gradle, gradle/wrapper/gradle-wrapper.properties
No issue
We have upgraded to the latest Android tools gradle plugin version
No screens
=> Upgraded to latest Android gradle plugin

.github/auto_assign.yml
No issue
It was not really fair that the same people reviews all the PRs so we have increased the list of possible reviewers.
No screens
=> Increased the number of reviewers for future PRs

leku/src/main/res/values-vi/strings.xml
I know a lot of vietnamese devs are using your libs, so I think I should translate english to vietnam for my community in Vietname.
Thanks, cool libs
=> add lang vietnamese

build.gradle, leku/build.gradle
No issue
We have updated some libraries in order to keep up-to-date the project
No screens
=> Update build tools gradle plugin and some libraries to keep up-to-date

README.md
no issue 
We corrected the bintray URL because the bintray user it's still the old schibsted org user
no screens
=> Correct mistake with bintray URL

build.gradle, leku/build.gradle, leku/src/main/res/layout/leku_toolbar_search.xml, leku/src/main/res/layout/leku_toolbar_search_legacy.xml
No Issue
We have updated the main libraries to the latest stable versions
No screens
=> [NO ISSUE] Upgrade project versions to latest

README.md, app/src/main/java/com/adevinta/mappicker/MainActivity.kt, app/src/main/res/values/strings.xml, gradle.properties, leku/src/main/AndroidManifest.xml, leku/src/main/java/com/adevinta/leku/LocationPickerActivity.kt, leku/src/main/res/values-es/strings.xml, leku/src/main/res/values/strings.xml
#327 #328 #329 
We have solved the issue with Address not being parsed correctly
No screens
=> Solved issues with Address parser and search address list

README.md, app/src/main/res/values/strings.xml, gradle.properties
We have a new release version with some fixes
#335 
#336 
#337
=> New release version 9.1.2

README.md, app/src/main/res/values/strings.xml, gradle.properties
No issue
We are going to make a new release version 9.1.3
No screens
=> New Release Version 9.1.3

README.md, app/src/main/res/values/strings.xml, gradle.properties, leku/src/main/java/com/adevinta/leku/LocationPickerActivity.kt, leku/src/main/java/com/adevinta/leku/geocoder/AndroidGeocoderDataSource.kt, leku/src/main/java/com/adevinta/leku/geocoder/GeocoderPresenter.kt, leku/src/main/java/com/adevinta/leku/geocoder/GeocoderViewInterface.kt
#339 #342
We have solved issue with error when already disposed or canceled flow.
No screens
=> [ISSUE 342] Solved issue with already disposed/canceled flow

README.md, app/src/main/java/com/adevinta/mappicker/MainActivity.kt, leku/src/main/java/com/adevinta/leku/LocationPickerActivity.kt
#345 
We have added the option to Hide the Search Bar
No screens
=> [ISSUE #345] - Added Hide option for the Search Bar

.github/workflows/docs-publish.yml, .gitignore, README.md, app/src/main/java/com/adevinta/mappicker/MainActivity.kt, docs/getting_started.md, docs/index.md, docs/license.md, docs/localization.md, mkdocs.yml
We have added a Github Action to automate the deploy of the documentation after merging a PR on master.
No screens
=> [NO ISSUE] Created CI yml for deploying Documentation automatically on merge

.github/workflows/docs-publish.yml
We have added the missing plugin to the CI workflow
No screens
=> Added missing plugin for Documentation CI

.github/auto_assign.yml
No Issue
Removed from auto-assign bot people not actively working on it.
No screens
=> Removed from the auto-assign list

gradle.properties, leku/src/main/java/com/adevinta/leku/utils/ReactiveLocationProvider.kt
No issue
We have solved an issue where a crash was raised when none of the location permissions where granted.
No screens
=> [NO ISSUE] Solved issue where none of the location permissions where granted returned an error

README.md, app/build.gradle, app/src/main/res/values/strings.xml, build.gradle, docs/extra.md, docs/getting_started.md, gradle.properties, gradle/wrapper/gradle-wrapper.properties, leku/build.gradle, leku/src/main/java/com/adevinta/leku/geocoder/AndroidGeocoderDataSource.kt, leku/src/main/java/com/adevinta/leku/geocoder/GeocoderDataSourceInterface.kt
No issue
We have upgraded the project to latest api 33 and updated the documentation
No screens
=> Upgraded to api 33 and updated documentation

leku/build.gradle
=> Update to last play-services-location version

gradle.properties
we need a new release version
Before | After
---|---
=> Change release version to 10.1.1

leku/build.gradle, leku/src/main/java/com/adevinta/leku/geocoder/GeocoderPresenter.kt
this lets the getLastKnownLocation() method launches
https://github.com/AdevintaSpain/Leku/issues/319
using current location button not working
=> Change CoroutineScope Dispatcher to IO

.github/workflows/android.yml, .github/workflows/publish.yml, README.md, app/build.gradle, app/src/main/java/com/adevinta/mappicker/MainActivity.kt, app/src/main/res/values/strings.xml, build.gradle, docs/getting_started.md, docs/license.md, gradle.properties, gradle/wrapper/gradle-wrapper.properties, leku/build.gradle, leku/src/main/java/com/adevinta/leku/LocationPickerActivity.kt, mkdocs.yml
No issue
We are solving all the issues we have encountered.
No screens
=> Upgraded project and general bug fixing

README.md, app/src/main/res/values/strings.xml, docs/getting_started.md, gradle.properties
No issue
Raised version to 11.1.2
No screens
=> Version 11.1.2

README.md, app/src/main/res/values/strings.xml, docs/getting_started.md, gradle.properties
=> Version 11.1.3

app/build.gradle.kts, leku/build.gradle.kts, scripts/publish-module.gradle
No issue
Solved issue when publishing metadata task dependency was not executed.
No screens
=> Solved issue when publishing metadata task dependency not executed

scripts/publish-module.gradle
=> added artifact again

app/build.gradle.kts, leku/build.gradle.kts, scripts/publish-module.gradle
=> Artifacts issu2

leku/build.gradle.kts, scripts/publish-module.gradle
=> Artifact issue try 3

scripts/publish-module.gradle
=> Artifact issue 4

scripts/publish-module.gradle
=> Artifact issue 5

.github/workflows/publish.yml
No issue
We have changed the user because the old one is not working anymore.
No screens
=> Changed to new Sonata user
